# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wedgeRcppParallel <- function(a1, b1, a2, b2, size_vect, tau, N, lower_tail) {
    .Call('wedgeParallel_wedgeRcppParallel', PACKAGE = 'wedgeParallel', a1, b1, a2, b2, size_vect, tau, N, lower_tail)
}

